---
consul::extra_options: '-ui'
consul::config_hash:
    server: true
    node_name: '%{trusted.hostname}'
    bootstrap_expect: 3
    datacenter: '%{::datacenter}'
    data_dir: '/var/consul'
    encrypt: 'X4SYObnf2pTAcAHRhpj7dA=='
    log_level: 'INFO'
    enable_syslog: true
    bind_addr: '%{::ipaddress_eth0}'
    addresses:
      rpc: "127.0.0.1"
      http: "0.0.0.0"
consul::services:
  consul-http-api:
    address: "%{::ipaddress_eth0}"
    checks:
      - script: "curl -I http://%{::ipaddress_eth0}:8500 >/dev/null 2>&1"
        interval: 10s
    port: 8500
    tags:
      - "consul-http-api"
