---
consul_template::version: '0.16.0'
consul_template::watches:
  'puppetmaster_backend':
    template: 'profiles/consul_template/templates/nginx_upstreams.erb'
    destination: '/etc/nginx/conf.stream.d/puppetmaster_backend-upstream.conf'
    template_vars:
      method: 'least_conn'
      backend_options: 'fail_timeout=10s'
      consul_service: 'puppetmaster'
    command: '/bin/systemctl reload nginx'
  'puppetdb_backend':
    template: 'profiles/consul_template/templates/nginx_upstreams.erb'
    destination: '/etc/nginx/conf.stream.d/puppetdb_backend-upstream.conf'
    template_vars:
      method: 'least_conn'
      backend_options: 'fail_timeout=10s'
      consul_service: 'puppetdb'
    command: '/bin/systemctl reload nginx'
  'consul_backend':
    template: 'profiles/consul_template/templates/nginx_upstreams.erb'
    destination: '/etc/nginx/conf.d/consul_backend-upstream.conf'
    template_vars:
      method: 'least_conn'
      backend_options: 'fail_timeout=10s'
      consul_service: 'consul-http-api'
    command: '/bin/systemctl reload nginx'
