---
consul::services:
  puppet:
    address: "%{::ipaddress_eth0}"
    checks:
      - script: "curl -I -k https://%{::ipaddress_eth0}:8140 >/dev/null 2>&1"
        interval: 10s
    port: 8140
    tags:
      - "puppet"
  puppetdb-lb:
    address: "%{::ipaddress_eth0}"
    checks:
      - script: "ps -ef | grep nginx | grep -v grep>/dev/null 2>&1"
        interval: 10s
    port: 8081
    tags:
      - "puppetdb-lb"
