# As we are now using r10k, this might be removed in the future

fixtures:
  forge_modules:
    bind:
      repo: "thias/bind"
      ref:  "0.5.3"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
    puppet:
      repo: "abstractit/puppet"
      ref: "2.2.1"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref: "5.1.2"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.6.0"
  symlinks:
    profiles: "#{source_dir}"
