source ENV['GEM_SOURCE'] || "https://rubygems.org"

group :development, :unit_tests do
  gem 'deep_merge',                                       '1.0.1',  :require => false
  gem 'metadata-json-lint',                               '0.0.11', :require => false
  gem 'puppet-catalog-test',                              '0.4.2',  :require => false
  gem 'puppet-lint-absolute_classname-check',             '0.1.3',  :require => false
  gem 'puppet-lint-alias-check',                          '0.1.0',  :require => false
  gem 'puppet-lint-empty_string-check',                   '0.2.2',  :require => false
  gem 'puppet-lint-file_ensure-check',                    '0.3.1',  :require => false
  gem 'puppet-lint-file_source_rights-check',             '0.1.0',  :require => false
  gem 'puppet-lint-fileserver-check',                     '1.2.1',  :require => false
  gem 'puppet-lint-leading_zero-check',                   '0.1.1',  :require => false
  gem 'puppet-lint-spaceship_operator_without_tag-check', '0.1.1',  :require => false
  gem 'puppet-lint-trailing_comma-check',                 '0.3.2',  :require => false
  gem 'puppet-lint-undef_in_function-check',              '0.2.1',  :require => false
  gem 'puppet-lint-unquoted_string-check',                '0.3.0',  :require => false
  gem 'puppet-lint-variable_contains_upcase',             '1.0.0',  :require => false
  gem 'puppet-lint-version_comparison-check',             '0.2.1',  :require => false
  gem 'puppet-lint',                                      '1.1.0',  :require => false
  gem 'puppetlabs_spec_helper',                           '1.1.1',  :require => false
  gem 'r10k',                                             '2.3.0',  :require => false
  gem 'rake',                                             '11.2.2', :require => false
  gem 'rspec-puppet-facts',                               '1.6.1',  :require => false
  gem 'rspec-puppet',                                     '2.4.0',  :require => false
  gem 'rspec',                                            '3.4.0',  :require => false
  gem 'yaml-lint',                                        '0.0.7',  :require => false
end

group :system_tests do
  gem 'beaker',                                           '2.44.0', :require => false
  gem 'beaker-rspec',                                     '5.4.0',  :require => false
  gem 'beaker_spec_helper',                               '0.1.0',  :require => false
  gem 'serverspec',                                       '2.36.0', :require => false
end

if facterversion = ENV['FACTER_GEM_VERSION']
  gem 'facter', facterversion, :require => false
else
  gem 'facter', :require => false
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
