---
consul::services:
  puppetdb:
    address: "%{::ipaddress_eth0}"
    checks:
      - script: "curl -I -k http://172.17.0.1:8080 >/dev/null 2>&1"
        interval: 10s
    port: 8081
    tags:
      - "puppetdb"
